### ISSUE TITLE
私聊可以正常发送，但是群聊不行

### ISSUE THREAD

**Issue by Shattered217** [monsterxcn/nonebot_plugin_epicfree#11]
```
03-31 12:01:25 [DEBUG] nonebot_plugin_epicfree | 获取到 6 个游戏数据：
Borderlands 3 Season Pass、Tunche、《消逝的光芒：增强版》、The Silent Age、《Blazing Sails》、Dishonored - Definitive Edition
03-31 12:01:25 [INFO] nonebot_plugin_epicfree | 跳过即将推出免费游玩的游戏：Borderlands 3 Season Pass(¥179.00)
03-31 12:01:25 [INFO] nonebot_plugin_epicfree | 跳过即将推出免费游玩的游戏：《消逝的光芒：增强版》(¥109.00)
03-31 12:01:25 [INFO] nonebot_plugin_epicfree | 跳过即将推出免费游玩的游戏：《Blazing Sails》(¥58.00)
03-31 12:01:25 [DEBUG] nonebot | OneBot V11 | Calling API send_group_forward_msg
03-31 12:01:33 [INFO] nonebot | Matcher(type='message', module=nonebot_plugin_epicfree) running complete
03-31 12:01:33 [ERROR] nonebot | Running Matcher(type='message', module=nonebot_plugin_epicfree) failed.
Traceback (most recent call last):
  File "<string>", line 17, in <module>
  File "/root/ac/.venv/lib/python3.10/site-packages/nonebot/__init__.py", line 273, in run
    get_driver().run(*args, **kwargs)
  File "/root/ac/.venv/lib/python3.10/site-packages/nonebot/drivers/fastapi.py", line 187, in run
    uvicorn.run(
  File "/root/ac/.venv/lib/python3.10/site-packages/uvicorn/main.py", line 568, in run
    server.run()
  File "/root/ac/.venv/lib/python3.10/site-packages/uvicorn/server.py", line 59, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/root/ac/.venv/lib/python3.10/site-packages/nonebot/message.py", line 141, in _check_matcher
    await _run_matcher(Matcher, bot, event, state, stack, dependency_cache)
> File "/root/ac/.venv/lib/python3.10/site-packages/nonebot/message.py", line 187, in _run_matcher
    await matcher.run(bot, event, state, stack, dependency_cache)
  File "/root/ac/.venv/lib/python3.10/site-packages/nonebot/internal/matcher/matcher.py", line 732, in run
    await self.simple_run(bot, event, state, stack, dependency_cache)
  File "/root/ac/.venv/lib/python3.10/site-packages/nonebot/internal/matcher/matcher.py", line 707, in simple_run
    await handler(
  File "/root/ac/.venv/lib/python3.10/site-packages/nonebot/dependencies/__init__.py", line 108, in __call__
    return await cast(Callable[..., Awaitable[R]], self.call)(**values)
  File "/root/ac/.venv/lib/python3.10/site-packages/nonebot_plugin_epicfree/__init__.py", line 34, in query_handle
    await bot.send_group_forward_msg(group_id=event.group_id, messages=free)  # type: ignore
  File "/root/ac/.venv/lib/python3.10/site-packages/nonebot/internal/adapter/bot.py", line 120, in call_api
    raise exception
  File "/root/ac/.venv/lib/python3.10/site-packages/nonebot/internal/adapter/bot.py", line 98, in call_api
    result = await self.adapter._call_api(self, api, **data)
  File "/root/ac/.venv/lib/python3.10/site-packages/nonebot/adapters/onebot/v11/adapter.py", line 140, in _call_api
    return handle_api_result(await self._result_store.fetch(seq, timeout))
  File "/root/ac/.venv/lib/python3.10/site-packages/nonebot/adapters/onebot/v11/utils.py", line 58, in handle_api_result
    raise ActionFailed(**result)
nonebot.adapters.onebot.v11.exception.ActionFailed: ActionFailed(data=None, echo='2', message='请参考 go-cqhttp 端输出', msg='SEND_MSG_API_ERROR', retcode=100, status='failed', wording='请参考 go-cqhttp 端输出')
03-31 12:01:33 [DEBUG] nonebot | Stop event propagation
```

**Comment by monsterxcn** [comment]
请参考 go-cqhttp 端输出

**Comment by Shattered217** [comment]
> 请参考 go-cqhttp 端输出

请问是参考go-cqhttp的文档吗，不是很能理解您的意思

**Comment by monsterxcn** [comment]
@Shattered217 看 go-cqhttp 的日志🥱

**Comment by Shattered217** [comment]
> @Shattered217 看 go-cqhttp 的日志🥱

感谢您的回复，是我账号的问题
