### ISSUE TITLE
获取限免游戏时失败

### ISSUE THREAD

**Issue by QSlotus** [monsterxcn/nonebot_plugin_epicfree#14]
获取限免游戏时失败
报错如下：
```
[INFO] nonebot_plugin_epicfree | 跳过即将推出免费游玩的游戏：《Fallout Tactics: Brotherhood of Steel》(¥41.00)
02-16 02:30:12 [INFO] nonebot_plugin_epicfree | 跳过即将推出免费游玩的游戏：《Fallout 2: A Post Nuclear Role Playing Game》(¥41.00)
02-16 02:30:12 [INFO] nonebot_plugin_epicfree | 跳过即将推出免费游玩的游戏：《Fallout: A Post Nuclear Role Playing Game》(¥41.00)
02-16 02:30:12 [INFO] nonebot | Matcher(type='message', module=nonebot_plugin_epicfree, lineno=27) running complete
02-16 02:30:12 [ERROR] nonebot | Running Matcher(type='message', module=nonebot_plugin_epicfree, lineno=27) failed.
Traceback (most recent call last):
  File "/data/nb/bot.py", line 21, in <module>
    nonebot.run(app="__mp_main__:app")
  File "/usr/local/lib/python3.10/dist-packages/nonebot/__init__.py", line 333, in run
    get_driver().run(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/nonebot/drivers/fastapi.py", line 185, in run
    uvicorn.run(
  File "/usr/local/lib/python3.10/dist-packages/uvicorn/main.py", line 587, in run
    server.run()
  File "/usr/local/lib/python3.10/dist-packages/uvicorn/server.py", line 62, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/local/lib/python3.10/dist-packages/nonebot/message.py", line 476, in check_and_run_matcher
    await _run_matcher(
> File "/usr/local/lib/python3.10/dist-packages/nonebot/message.py", line 428, in _run_matcher
    await matcher.run(bot, event, state, stack, dependency_cache)
  File "/usr/local/lib/python3.10/dist-packages/nonebot/internal/matcher/matcher.py", line 842, in run
    await self.simple_run(bot, event, state, stack, dependency_cache)
  File "/usr/local/lib/python3.10/dist-packages/nonebot/internal/matcher/matcher.py", line 817, in simple_run
    await handler(
  File "/usr/local/lib/python3.10/dist-packages/nonebot/dependencies/__init__.py", line 106, in __call__
    return await cast(Callable[..., Awaitable[R]], self.call)(**values)
  File "/usr/local/lib/python3.10/dist-packages/nonebot_plugin_epicfree/__init__.py", line 34, in query_handle
    await bot.send_group_forward_msg(group_id=event.group_id, messages=free)  # type: ignore
  File "/usr/local/lib/python3.10/dist-packages/nonebot/internal/adapter/bot.py", line 122, in call_api
    raise exception
  File "/usr/local/lib/python3.10/dist-packages/nonebot/internal/adapter/bot.py", line 97, in call_api
    result = await self.adapter._call_api(self, api, **data)
  File "/usr/local/lib/python3.10/dist-packages/nonebot/adapters/onebot/v11/adapter.py", line 147, in _call_api
    return handle_api_result(await self._result_store.fetch(seq, timeout))
  File "/usr/local/lib/python3.10/dist-packages/nonebot/adapters/onebot/v11/utils.py", line 58, in handle_api_result
    raise ActionFailed(**result)
nonebot.adapters.onebot.v11.exception.ActionFailed: ActionFailed(status='failed', retcode=404, data=None, echo='9')
```

**Comment by FlanChanXwO** [comment]
现在修了，老哥
