### ISSUE TITLE
UnboundLocalError: local variable 'msg' referenced before assignment

### ISSUE THREAD

**Issue by zhufree** [monsterxcn/nonebot_plugin_epicfree#7]
```
07-30 19:37:31 [ERROR] nonebot | Running matcher <Matcher from nonebot_plugin_epicfree, type=message, priority=2, temp=False> failed.
Traceback (most recent call last):
  File "/home/ubuntu/.pyenv/versions/3.9.5/bin/nb", line 8, in <module>
    sys.exit(main())
  File "/home/ubuntu/.pyenv/versions/3.9.5/lib/python3.9/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/home/ubuntu/.pyenv/versions/3.9.5/lib/python3.9/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/home/ubuntu/.pyenv/versions/3.9.5/lib/python3.9/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/ubuntu/.pyenv/versions/3.9.5/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/ubuntu/.pyenv/versions/3.9.5/lib/python3.9/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/ubuntu/.pyenv/versions/3.9.5/lib/python3.9/site-packages/nb_cli/commands/main.py", line 30, in run
    run_bot(file, app)
  File "/home/ubuntu/.pyenv/versions/3.9.5/lib/python3.9/site-packages/nb_cli/handlers/deploy.py", line 23, in run_bot
    nonebot.run()
  File "/home/ubuntu/.pyenv/versions/3.9.5/lib/python3.9/site-packages/nonebot/__init__.py", line 261, in run
    get_driver().run(*args, **kwargs)
  File "/home/ubuntu/.pyenv/versions/3.9.5/lib/python3.9/site-packages/nonebot/drivers/fastapi.py", line 170, in run
    uvicorn.run(
  File "/home/ubuntu/.pyenv/versions/3.9.5/lib/python3.9/site-packages/uvicorn/main.py", line 463, in run
    server.run()
  File "/home/ubuntu/.pyenv/versions/3.9.5/lib/python3.9/site-packages/uvicorn/server.py", line 60, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "/home/ubuntu/.pyenv/versions/3.9.5/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/home/ubuntu/.pyenv/versions/3.9.5/lib/python3.9/site-packages/nonebot/message.py", line 146, in _check_matcher
    await _run_matcher(Matcher, bot, event, state, stack, dependency_cache)
> File "/home/ubuntu/.pyenv/versions/3.9.5/lib/python3.9/site-packages/nonebot/message.py", line 196, in _run_matcher
    await matcher.run(bot, event, state, stack, dependency_cache)
  File "/home/ubuntu/.pyenv/versions/3.9.5/lib/python3.9/site-packages/nonebot/internal/matcher.py", line 668, in run
    await self.simple_run(bot, event, state, stack, dependency_cache)
  File "/home/ubuntu/.pyenv/versions/3.9.5/lib/python3.9/site-packages/nonebot/internal/matcher.py", line 635, in simple_run
    await handler(
  File "/home/ubuntu/.pyenv/versions/3.9.5/lib/python3.9/site-packages/nonebot/dependencies/__init__.py", line 92, in __call__
    return await self.call(**values)
  File "/home/ubuntu/.pyenv/versions/3.9.5/lib/python3.9/site-packages/nonebot_plugin_epicfree/__init__.py", line 28, in onceHandle
    imfree = await getEpicFree()
  File "/home/ubuntu/.pyenv/versions/3.9.5/lib/python3.9/site-packages/nonebot_plugin_epicfree/data_source.py", line 121, in getEpicFree
    return msg
```
有空修吗，没有空我就自己试着改改提pr

**Comment by monsterxcn** [comment]
可以 git pull 一下看看，之前写没注意，现在开了 Pylance 好多了。如果是 pip 安装的话我暂未发版，等你反馈，有问题 reopen issue～

**Comment by zhufree** [comment]
看了你代码应该是OK的，我这个问题就是访问301了没拿到内容所以报错了

**Comment by monsterxcn** [comment]
301 的话试试 `client.post()` 里跟随重定向 `follow_redirects=True`，下次更新我再加上。今天顺便更新了调用的 API 地址，看别人早就换了，不过我一直用旧的地址也可以获取数据就没管。
